### ISSUE TITLE
Внешние баги

### ISSUE THREAD

**Issue by EvgeniyChuprov** [iatsdotfatr/4th-task#2]
Не сдвинуть меньший ползунок, если ползунки вместе.
![Peek 2019-12-24 12-26](https://user-images.githubusercontent.com/36810364/71406305-ce5e2a80-2648-11ea-9628-f1724590d715.gif)
+ по идее при клике на полосу слайдера ползунок должен вставать в место клика

**Comment by EvgeniyChuprov** [comment]
Еще один всплыл
![Peek 2019-12-26 13-43](https://user-images.githubusercontent.com/36810364/71472877-c25b9f80-27e5-11ea-9c7e-89f7a5f04ac2.gif)

**Comment by EvgeniyChuprov** [comment]
Шкала себя странно ведет при небольшой разнице между min и max
![Снимок экрана от 2019-12-27 14-08-35](https://user-images.githubusercontent.com/36810364/71515074-85a9aa00-28b2-11ea-9c77-657a01aa9281.png)

![Peek 2019-12-27 14-15](https://user-images.githubusercontent.com/36810364/71515255-64958900-28b3-11ea-8f28-bca5ffea824d.gif)

Если последний шаг не совпадает с максимумом шкалы он по идее совершаться не должен.
Ну и отрицательная шкала снова странно себя ведет.
![Peek 2019-12-27 14-28](https://user-images.githubusercontent.com/36810364/71515635-4e88c800-28b5-11ea-950e-1ac854a74906.gif)

**Comment by iatsdotfatr** [comment]
Поправил
